# Generated by Django 4.0.6 on 2022-08-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('loc', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=50)),
                ('img_path', models.TextField()),
                ('theme_number', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('theme', models.TextField()),
                ('img_path', models.TextField()),
                ('genre', models.CharField(max_length=255)),
                ('people', models.CharField(default='-', max_length=30)),
                ('info', models.TextField(default='-')),
                ('difficulty', models.IntegerField(default=0)),
                ('horror', models.IntegerField(default=0)),
                ('activity', models.IntegerField(default=0)),
                ('star', models.IntegerField(default=0)),
                ('recommend', models.IntegerField(default=0)),
                ('room', models.ForeignKey(db_column='room', on_delete=django.db.models.deletion.CASCADE, related_name='theme_room', to='room_escape.room')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeReview',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=1000)),
                ('difficulties', models.IntegerField(default=0)),
                ('activeness', models.IntegerField(default=0)),
                ('horrors', models.IntegerField(default=0)),
                ('stars', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='ThemeReview_email', to='room_escape.member')),
                ('theme', models.ForeignKey(db_column='theme', on_delete=django.db.models.deletion.CASCADE, related_name='ThemeReview_theme', to='room_escape.theme')),
            ],
        ),
        migrations.CreateModel(
            name='CafeReview',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=1000)),
                ('stars', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='CafeReview_email', to='room_escape.member')),
                ('room', models.ForeignKey(db_column='room', on_delete=django.db.models.deletion.CASCADE, related_name='CafeReview_room', to='room_escape.room')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('title', models.TextField(max_length=1000)),
                ('content', models.TextField()),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('hit', models.PositiveIntegerField(default=0)),
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='board_email', to='room_escape.member')),
            ],
        ),
    ]
