# Generated by Django 4.1 on 2022-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_escape", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="no",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="cafereview",
            name="no",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="no",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="theme",
            name="no",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="themereview",
            name="no",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
