# Generated by Django 4.0.6 on 2022-08-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_escape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
