# Generated by Django 4.0.6 on 2022-08-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_escape', '0002_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='board_email', to='room_escape.member'),
        ),
    ]
