# Generated by Django 4.1 on 2022-08-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_escape", "0003_alter_board_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafereview",
            name="no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="theme",
            name="no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="themereview",
            name="no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
