# Generated by Django 4.1 on 2022-08-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "room_escape",
            "0002_alter_board_no_alter_cafereview_no_alter_room_no_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="no",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
