# Generated by Django 4.1 on 2022-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "room_escape",
            "0004_alter_cafereview_no_alter_room_no_alter_theme_no_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="room", name="img_path", field=models.TextField(default="0"),
        ),
    ]
