# Generated by Django 4.1 on 2022-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_escape", "0005_room_img_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room", name="img_path", field=models.TextField(),
        ),
    ]
